config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  get 'notices/show'
  root 'pages#home'
  get '/about', to: "pages#about"
  get '/discord', to: "pages#discord"

  namespace :admin do
    get 'pages/home'
    get 'users/index'
    get 'contacts/index'
    patch 'contacts/update'

    resources :posts, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch "publicate"
        patch "withdraw"
      end

      resources :dtopics, only: [:create, :destroy] do
        member do
          patch "d_choose"
          patch "d_omit"
        end
      end

      resources :itopics, only: [:create, :destroy] do
        member do
          patch "i_choose"
          patch "i_omit"
        end
      end
      
      resources :comments, only: [:create, :destroy] 
    end

    resources :users do
      member do
        patch "set_admin"
        patch "remove_admin"
      end
    end

    resources :notices, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch "publicate"
        patch "withdraw"
      end
    end

    resources :videos
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :videos, only: [:index]
  resources :posts, only: [:index]
  resources :contacts, only: [:create]
  resources :notices, only: [:index, :show]

  namespace :likes do
    post 'comment_like'
    delete 'comment_dislike'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :likes, as: :object, dependent: :destroy

  validates :content, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :content, presence: true

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: {maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/models/dtopic.rb
class Dtopic < ApplicationRecord
  belongs_to :post

  validates :content, presence: true, length: { maximum: 42 }
end

app/models/itopic.rb
class Itopic < ApplicationRecord
  belongs_to :post

  validates :content, presence: true, length: { maximum: 42 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :object, polymorphic: true
  default_scope { order(created_at: :desc) }
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :dtopics, dependent: :destroy
  has_many :itopics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, as: :object, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :contacts, dependent: :destroy
  
  mount_uploader :picture, PictureUploader
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 170 }

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: {maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :picture, PictureUploader

  validates :link, presence: true
  validates :title, presence: true
  validates :picture, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def comment_like
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    @comment.likes.create(user_id: current_user.id)

    redirect_to edit_admin_post_url(@post, anchor: "comment")
  end

  def comment_dislike
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    @like = Like.find(params[:like_id])
    @like.destroy

    redirect_to edit_admin_post_url(@post, anchor: "comment")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    # 渡された情報(user)のidでログインする
    session[:user_id] = user.id
  end

  def current_user
    # 変数の値がnilなら変数に代入するが、nilでなければ代入しない (変数の値を変えない)
    # @current_user=current_user OR User.find_by(id: session[user_id])をやってる
    # @current_user =@current_user || User.find_by(id: session[user_id]と下のコードは等しい
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    # ユーザーがログインしていればtrue、その他ならfalseを返す
    !current_user.nil?
  end

  def logout(user)
    session.delete(:user_id)
    # こやつを書いていなかった吉田は１週間以上エラーでした
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def btn_color(status)
    @filter == status ? "btn-dark" : "btn-outline-dark"
  end

  def admin_user(user)
    if user.is_admin == true
      "font-weight-bold"
    end
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/pages/home.erb
<section class="admin-home container text-center pt-5">
    <h1 class="my-5 pt-5 title">管理メンバー<br>ホーム</h1>
    <div class="px-5 mt-5">
        <div class="row justify-content-center mb-4">
            <div class="col-12 col-md-4 col-md-4 mb-3">
                <%= link_to admin_users_index_path, class: "text-dark link" do %>
                    <div class="card card-body shadow hover">
                        <h3>メンバーリスト</h3>
                        <i class="fas fa-users-cog fa-5x"></i>
                    </div>
                <% end %>
            </div>
            <div class="col-12 col-md-4 mb-3">
                <%= link_to admin_posts_path, class: "text-dark link" do %>
                    <div class="card card-body shadow hover">
                        <h3>投稿作成・編集</h3>
                        <i class="fas fa-newspaper fa-5x"></i>
                    </div>
                <% end %>
            </div>
            <div class="col-12 col-md-4 mb-3">
                <%= link_to admin_videos_path, class: "text-dark link" do %>
                    <div class="card card-body shadow hover">
                        <h3>動画掲示板</h3>
                        <i class="fas fa-file-video fa-5x"></i>
                    </div>
                <% end %>
            </div>
            <div class="col-12 col-md-4 mb-3 ml-auto">
                <%= link_to admin_contacts_index_path, class: "text-dark link" do %>
                    <div class="card card-body shadow hover">
                        <h3>質問管理</h3>
                        <i class="fas fa-chalkboard-teacher fa-5x"></i>
                    </div>
                <% end %>
            </div>

            <div class="col-12 col-md-4 mb-3 mr-auto mb-5">
                <%= link_to admin_notices_path, class: "text-dark link" do %>
                    <div class="card card-body shadow hover">
                        <h3>お知らせ管理 </h3>
                        <i class="fas fa-info-circle fa-5x"></i>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/layouts/_footer.html.erb
<%= link_to 'javascript:history.back()', class: "back-button" do %>
    <i class="fas fa-fast-backward"></i>
<% end %>

<section class="bg-light">
    <div class="text-right mr-5 pt-3">
        <%= link_to "ホーム", root_path, class: "text-dark pr-3" %>
        <%= link_to "ボフボフネットについて", about_path, class: "text-dark" %>
    </div>
    <p class="text-muted text-center m-0 py-3">All Rights Reserved &copy;Bofbof_net</p>
</section>

app/views/layouts/_header.html.erb
<section class="position-relative">
    <div class="logo-section">
        <%= link_to root_path do %>
            <%= image_tag "BOFBOF_LOGO.png", class:"logo" %>
        <% end %>
    </div>
    <div class="sns-wapper">
        <div class="sns-button b1">
            <div class="icon">
                <%= link_to "https://www.instagram.com/bofbof_net/?hl=en", target: :_blank, class: "text-dark" do %>
                    <i class="fab fa-instagram"></i>
                <% end %>
            </div>
            <span>Instagram</span>
        </div><br>
        <div class="sns-button b2">
            <div class="icon">
                <%= link_to discord_path, class: "text-dark" do %>
                    <i class="fab fa-discord"></i>
                <% end %>
            </div>
            <span>Discord</span>
        </div><br>
        <div class="sns-button b3">
            <div class="icon">
                <%= link_to "https://www.youtube.com/channel/UCSmbxJi_wgyFNr2X4Z5YIcw", target: :_blank, class: "text-dark" do %>
                    <i class="fab fa-youtube"></i>
                <% end %>
            </div>
            <span>YouTube</span>
        </div><br>
        <div class="sns-button b4">
            <div class="icon">
                <%= link_to "https://twitter.com/bofbofnet", target: :_blank, class: "text-dark" do %>
                    <i class="fab fa-twitter"></i>
                <% end %>
            </div>
            <span>Twitter</span>
        </div>
    </div>
    <div class="menu-wrap">
        <input type="checkbox" class="toggler">
        <div class="hamburger"><div></div></div>
        <div class="menu font-weight-bold">
            <div class="row">
                <div class="col-6 text-right">
                    <ul>
                        <li><%= link_to "ホーム", root_path, class:"cool-link" %></li>
                        <li><%= link_to "ニュース投稿を見る", posts_path, class:"cool-link" %></li>
                        <li><%= link_to "YouTubeをチェックする", videos_path, class:"cool-link" %></li>
                        <li><%= link_to "メンバー紹介", users_path, class:"cool-link" %></li>
                        <li><%= link_to "ボフボフネットについて", about_path, class:"cool-link" %></li>
                    </ul>
                </div>
                <div class="col-6 text-left">
                    <ul >
                        <% if logged_in? %>
                            <li><span class="orange"><i class="fas fa-exclamation-circle"></i>現在ログイン中</span></li>
                            <%if current_user.is_admin == true %>
                                <li><%= link_to "管理メンバーページ", admin_pages_home_path, class:"cool-link" %><br></li>
                            <% end %>
                            <li><%= link_to "プロフィール", user_path(current_user.id), class:"cool-link" %><br></li>
                            <li><%= button_to session_path(current_user), method: :delete, class: "btn btn-link p-0" do %>
                                    <span class="cool-link logout">ログアウト</span>
                                <% end %>
                            </li>
                        <% else %>
                            <li><%= link_to "サインイン", new_user_path, class:"cool-link" %><br></li>
                            <li><%= link_to "ログイン", new_session_path, class:"cool-link" %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BofbofNet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
  </head>

  <body>
    <%= render "layouts/header" %>

    <br>
    <% if flash.any? %>
      <script type="text/javascript">
          <% flash.each do |type, value| %>
              toastr['<%= type %>']('<%= value %>')
          <% end %>
      </script>
    <% end %>

    <%= yield %>
    <br>
    <%= render "layouts/footer" %>
  </body>
</html>