config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  get 'notices/show'
  root 'pages#home'
  get '/about', to: "pages#about"
  get '/discord', to: "pages#discord"

  namespace :admin do
    get 'pages/home'
    get 'users/index'
    get 'contacts/index'
    patch 'contacts/update'

    resources :posts, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch "publicate"
        patch "withdraw"
      end

      resources :dtopics, only: [:create, :destroy] do
        member do
          patch "d_choose"
          patch "d_omit"
        end
      end

      resources :itopics, only: [:create, :destroy] do
        member do
          patch "i_choose"
          patch "i_omit"
        end
      end
      
      resources :comments, only: [:create, :destroy] 
    end

    resources :users do
      member do
        patch "set_admin"
        patch "remove_admin"
      end
    end

    resources :notices, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch "publicate"
        patch "withdraw"
      end
    end

    resources :videos
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :videos, only: [:index]
  resources :posts, only: [:index]
  resources :contacts, only: [:create]
  resources :notices, only: [:index, :show]

  namespace :likes do
    post 'comment_like'
    delete 'comment_dislike'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :likes, as: :object, dependent: :destroy

  validates :content, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :content, presence: true

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: {maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/models/dtopic.rb
class Dtopic < ApplicationRecord
  belongs_to :post

  validates :content, presence: true, length: { maximum: 42 }
end

app/models/itopic.rb
class Itopic < ApplicationRecord
  belongs_to :post

  validates :content, presence: true, length: { maximum: 42 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :object, polymorphic: true
  default_scope { order(created_at: :desc) }
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :dtopics, dependent: :destroy
  has_many :itopics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, as: :object, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :contacts, dependent: :destroy
  
  mount_uploader :picture, PictureUploader
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 170 }

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: {maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :picture, PictureUploader

  validates :link, presence: true
  validates :title, presence: true
  validates :picture, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_login
  before_action :require_admin
  
  def index
    @filter = params[:user_filter]
    if @filter == "admin"
      @users = User.where(is_admin: true).paginate(page: params[:page], per_page: 8)
    elsif @filter == "non-admin"
      @users = User.where(is_admin: false).paginate(page: params[:page], per_page: 8)
    else
      @users = User.paginate(page: params[:page], per_page: 8)
    end
  end

  def set_admin
    @user = User.find(params[:id])
    @user.update(is_admin: true)

    redirect_back(fallback_location: request.referer)
  end

  def remove_admin
    @user = User.find(params[:id])
    @user.update(is_admin: false)

    redirect_back(fallback_location: request.referer)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def comment_like
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    @comment.likes.create(user_id: current_user.id)

    redirect_to edit_admin_post_url(@post, anchor: "comment")
  end

  def comment_dislike
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    @like = Like.find(params[:like_id])
    @like.destroy

    redirect_to edit_admin_post_url(@post, anchor: "comment")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @notices = Notice.where(to_show: true)
    @contact = Contact.new
    @users = User.where(is_admin: true).paginate(page: params[:page], per_page: 4)
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @active_posts = Post.where(is_active: true)
    @q = @active_posts.ransack(params[:q])
    @posts = @q.result(distinct: true).paginate(page: params[:page], per_page: 6)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "サインインに成功しました！"


      redirect_to new_session_url
    else
      flash[:error] = "サインインできませんでした。情報をご確認のうえ、もう一度お試しください。"
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      render "show"
    else
      render "edit"
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 8)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture, :uni, :year, :description, :is_admin)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    # 渡された情報(user)のidでログインする
    session[:user_id] = user.id
  end

  def current_user
    # 変数の値がnilなら変数に代入するが、nilでなければ代入しない (変数の値を変えない)
    # @current_user=current_user OR User.find_by(id: session[user_id])をやってる
    # @current_user =@current_user || User.find_by(id: session[user_id]と下のコードは等しい
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    # ユーザーがログインしていればtrue、その他ならfalseを返す
    !current_user.nil?
  end

  def logout(user)
    session.delete(:user_id)
    # こやつを書いていなかった吉田は１週間以上エラーでした
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def btn_color(status)
    @filter == status ? "btn-dark" : "btn-outline-dark"
  end

  def admin_user(user)
    if user.is_admin == true
      "font-weight-bold"
    end
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/users/index.html.erb
<section class="admin-users container text-center pt-5 mb-5">
    <h1 class="pt-5 mt-5 title">メンバーリスト</h1>
    <div class="row mx-3">
        <div class="col-12 col-md-4 mt-5 mb-2 px-5">
            <div class="row justify-content-center">
                <div class="col-4 px-0">
                    <%= link_to "すべて", admin_users_index_path(user_filter: "all"), class:"btn btn-block #{btn_color("all")}" %>
                </div>
                <div class="col-4 px-0">
                    <%= link_to "管理者", admin_users_index_path(user_filter: "admin"), class:"btn btn-block #{btn_color("admin")}" %>
                </div>
                <div class="col-4 px-0">
                    <%= link_to "非管理者", admin_users_index_path(user_filter: "non-admin"), class:"btn btn-block #{btn_color("non-admin")}" %>
                </div>
            </div>
        </div>
    </div>
    <div class="card mx-5">
        <div class="card-header py-1">
            <div class="row">
                <div class="col-4 col-md-2">名前</div>
                <div class="col-4 col-md-4">Eメール</div>
                <div class="col-4 col-md-3">大学</div>
            </div>
        </div>
        <div class="card-body ">
            <% if !@users.any? %>
                <h4 class="text-muted">まだメンバーがいません。</h4>
            <% else %>
                <% @users.each do |user| %>
                    <div class="row py-0">
                        <div class="col-4 col-md-2 my-auto">
                            <% if user.is_admin == true %>
                                <small class="ml-auto"><span class="badge badge-pill remove-btn">管理者</span></small><br>
                            <% end %>
                            <span class="<%= admin_user(user) %>"><%= link_to user.name, user_path(user) %></span>
                        </div>
                        <div class="col-4 col-md-4 my-auto">
                            <%= user.email %>
                        </div>
                        <div class="col-4 col-md-3 my-auto">
                            <%= user.uni %>
                        </div>
                        <div class="col-4 col-md-3 my-auto ml-auto">
                            <% if user.is_admin == true %>
                                <%= button_to "管理者解除", remove_admin_admin_user_path(user), method: :patch, class: "btn btn-outline-dark" %>
                            <% else %>
                                <%= button_to "管理者にする", set_admin_admin_user_path(user), method: :patch, class: "btn btn-outline-dark remove-btn" %>
                            <% end %>
                        </div>
                    </div>
                    <hr>
                <% end %> 
            <% end %>
        </div>   
    </div>
    <div class="row">
        <div class="col-6 mx-auto px-auto mt-5">
            <div class="put-center"><%= will_paginate @users %></div>
        </div>
    </div>
</section>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger text-danger" role="alert">
        <p> The form contains <%= pluralize(@user.errors.count, "error") %> </p>
        <hr>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %> </li>
            <% end %>
        </ul>
    </div>  
<% end %>

app/views/users/_form.html.erb
<div class="row">
    <div class="col-6 m-auto">
        <hr>
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <%= form_for @user do |f| %>
                    <%= render "error_messages" %>
                        <%= f.label :name, "名前" %>
                        <%= f.text_field :name, class: "form-control" %>

                        <%= f.label :email, "メールアドレス" %>
                        <%= f.email_field :email, class: "form-control" %>

                        <%= f.label :password, "パスワード" %>
                        <%= f.password_field :password, class: "form-control" %>

                        <%= f.label :password_confirmation, "確認用パスワード" %>
                        <%= f.password_field :password_confirmation, class: "form-control" %>

                        <br>
                        <%= f.submit btn_name, class: "btn btn-outline-dark bg-color btn-block" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<section class="row">
    <div class="col-6 m-auto">
        <hr>
        <div class="card">
            <div class="card-body">
                <%= form_for @user do |f| %>
                <%= render "error_messages" %>
                    <% if logged_in? %>
                        <%= f.label :picture, "写真" %>
                        <%= f.file_field :picture, class: "form-control" %>
                        <p class="my-0 text-muted">* 横幅が大きい画像推奨</p>
                    <% end %>
                    <%= f.label :name, "名前" %>
                    <%= f.text_field :name, class: "form-control" %>

                    <%= f.label :email, "メールアドレス" %>
                    <%= f.email_field :email, class: "form-control" %>

                    <%= f.label :password, "パスワード" %>
                    <%= f.password_field :password, class: "form-control" %>

                    <%= f.label :password_confirmation, "確認用パスワード" %>
                    <%= f.password_field :password_confirmation, class: "form-control" %>

                    <%# add a uni form %>
                    <%= f.label :uni, "大学名" %>
                    <%= f.text_field :uni, class: "form-control", :placeholder => "大学名"%>

                    <%# add a year form %>
                    <%= f.label :year, "何年生" %>
                    <%= f.text_field :year, class: "form-control", :placeholder => "半角数字で入力してください" %>

                    <%# add a description form %>
                    <%= f.label :description, "自己紹介" %>
                    <%= f.text_area :description, class: "form-control",:placeholder => "5行くらいがベスト！" %>

                    <br>
                    <%= f.submit "保存", class: "btn btn-outline-dark bg-color btn-block" %>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/users/index.html.erb
<section class="admin-home container text-center pt-5">
    <h1 class="mb-5 pt-5 title text-white">BOFBOFメンバー</h1>
    <div class="mt-3">
        <div class="pl-5">
            <%= image_tag "people.png", class:"w-100" %><br>
        </div>
        
        <div class="content text-center font-weight-bold">
            <p  class="mt-4 section-title-s mb-5 pb-5">
                BOFBOF NETは全国の大学生によって企画・運営される学生団体。<br>
                メンバーや活動内容ついて知って<br>
                興味がでたらあなたもBOFBOFの一員になろう！！
            </p>
        </div>
        <div class="row mx-5 text-black">
            <% @users.each do |user| %>
                <div class="col-6 col-md-4">
                    <div class="bg-white p-4 mx-1">
                        <%= link_to user_path(user) do %>
                            <% if user.picture? %>
                                <%= image_tag user.picture.url, class: "hover w-100"  %>
                            <% else %>
                                <%= image_tag gravatar_for(user), class: "hover w-100" %>
                            <% end %>
                        <% end %><br>
                        <% if user.uni %>
                            <div class="badge badge-pill badge-dark">
                                <%= user.uni %>大学 <%= user.year %>年
                            </div><br>
                        <% else %>
                            
                        <% end %>
                        <%= link_to user.name, user_path(user), class: "text-dark font-weight-bold" %><br>
                        
                        <small><%= user.description %></small>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-6 mx-auto px-auto mt-5">
            <div class="put-center"><%= will_paginate @users %></div>
        </div>
    </div>
</section>

app/views/users/new.html.erb
<div class="container text-center">
    <h1 class=" text-white title mb-5"><br>サインイン</h1>
    <div class="text-left mt-5">
        <%= render "form", btn_name: "サインインする" %>
    </div>
    <br>
    <p>
    もうすでにアカウントをお持ちの方は<span class="orange"><%= link_to "こちら", new_session_path %></span>
    </p>
</div>

app/views/users/show.html.erb
<section class="container pt-5">
    <div class="row mb-4 mx-5 mt-5">
        <div class="col-12 col-md-6 p-5 bg-white">
            <%# 画像表示 %>
            <% if @user.picture? %>
                <%= image_tag @user.picture.url, class: "profile-pic w-100 m-5" %>
            <% else %>
                <%= image_tag gravatar_for(@user), class: "profile-pic w-100" %>
            <% end %>
        </div>
        <div class="col-12 col-md-6 bg-white text-center">
            <br>
            <%# name %>
            <h1 class="section-title mx-3 mt-3"><%= @user.name %></h1>
            <%# uni and year %>
            <% if @user.uni %>
            <p class=""><span><%= @user.uni %>大学</span>
                <% if @user.year? %>
                    <span><%= @user.year %>年生</span>
                <% end %>
            </p>
            <% end %>
            <% if @user.description? %>
                <p class="text-center profile-p orange px-5 pb-5 pt-3"><%= @user.description %></p><br>
            <% else %>
                <h5 class="text-center orange p-5">情報がありません。</h5>
            <% end %>
            <% if logged_in? %>
                <% if current_user.id == @user.id %>
                    <%# edit botton %>
                    <%= link_to "編集", edit_user_path, class: "btn btn-outline-dark bg-color py-0 text-center prof-button" %>
                <% end %>
            <% end %>
        </div>
    </div>
</section>