config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  get 'notices/show'
  root 'pages#home'
  get '/about', to: "pages#about"
  get '/discord', to: "pages#discord"

  namespace :admin do
    get 'pages/home'
    get 'users/index'
    get 'contacts/index'
    patch 'contacts/update'

    resources :posts, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch "publicate"
        patch "withdraw"
      end

      resources :dtopics, only: [:create, :destroy] do
        member do
          patch "d_choose"
          patch "d_omit"
        end
      end

      resources :itopics, only: [:create, :destroy] do
        member do
          patch "i_choose"
          patch "i_omit"
        end
      end
      
      resources :comments, only: [:create, :destroy] 
    end

    resources :users do
      member do
        patch "set_admin"
        patch "remove_admin"
      end
    end

    resources :notices, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch "publicate"
        patch "withdraw"
      end
    end

    resources :videos
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :videos, only: [:index]
  resources :posts, only: [:index]
  resources :contacts, only: [:create]
  resources :notices, only: [:index, :show]

  namespace :likes do
    post 'comment_like'
    delete 'comment_dislike'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :likes, as: :object, dependent: :destroy

  validates :content, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :content, presence: true

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: {maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/models/dtopic.rb
class Dtopic < ApplicationRecord
  belongs_to :post

  validates :content, presence: true, length: { maximum: 42 }
end

app/models/itopic.rb
class Itopic < ApplicationRecord
  belongs_to :post

  validates :content, presence: true, length: { maximum: 42 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :object, polymorphic: true
  default_scope { order(created_at: :desc) }
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :dtopics, dependent: :destroy
  has_many :itopics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, as: :object, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :contacts, dependent: :destroy
  
  mount_uploader :picture, PictureUploader
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 170 }

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: {maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :picture, PictureUploader

  validates :link, presence: true
  validates :title, presence: true
  validates :picture, presence: true
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  def index
    @videos = Video.paginate(page: params[:page], per_page: 8)
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = "動画情報をアップしました！"

      redirect_to admin_videos_url
    else 
      flash[:error] = "動画情報をアップできませんでした。もう一度試してください！"

      redirect_back(fallback_location: request.referer)
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.update(video_params)
      flash[:success] = "動画情報を変更しました！"

      redirect_to admin_videos_url
    else
      flash[:error] = "動画情報を変更できませんでした。もう一度試してください！"

      redirect_back(fallback_location: request.referer)
    end
  end

  def destroy
    @video = Video.find(params[:id])
    if @video.destroy
      flash[:success] = "動画投稿を削除しました！"
    else
      flash[:error] = "削除に失敗しました。"
    end
    redirect_back(fallback_location: request.referer)
  end

  def video_params
    params.require(:video).permit(:link, :title, :content, :picture)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def comment_like
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    @comment.likes.create(user_id: current_user.id)

    redirect_to edit_admin_post_url(@post, anchor: "comment")
  end

  def comment_dislike
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    @like = Like.find(params[:like_id])
    @like.destroy

    redirect_to edit_admin_post_url(@post, anchor: "comment")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @notices = Notice.where(to_show: true)
    @contact = Contact.new
    @users = User.where(is_admin: true).paginate(page: params[:page], per_page: 4)
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @active_posts = Post.where(is_active: true)
    @q = @active_posts.ransack(params[:q])
    @posts = @q.result(distinct: true).paginate(page: params[:page], per_page: 6)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @q = Video.ransack(params[:q])
    @videos = @q.result(distinct: true).paginate(page: params[:page], per_page: 4)
  end

  def show
    @video = Video.find(params[:id])
  end
end

app/helpers/admin/videos_helper.rb
module Admin::VideosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    # 渡された情報(user)のidでログインする
    session[:user_id] = user.id
  end

  def current_user
    # 変数の値がnilなら変数に代入するが、nilでなければ代入しない (変数の値を変えない)
    # @current_user=current_user OR User.find_by(id: session[user_id])をやってる
    # @current_user =@current_user || User.find_by(id: session[user_id]と下のコードは等しい
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    # ユーザーがログインしていればtrue、その他ならfalseを返す
    !current_user.nil?
  end

  def logout(user)
    session.delete(:user_id)
    # こやつを書いていなかった吉田は１週間以上エラーでした
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def btn_color(status)
    @filter == status ? "btn-dark" : "btn-outline-dark"
  end

  def admin_user(user)
    if user.is_admin == true
      "font-weight-bold"
    end
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/videos/_video_form.html.erb
<%= form_for([:admin, @video]) do |f| %>
    <div class="row mx-5 my-3">
        <div class="col-12 col-md-6 my-auto">
            <%= f.label :picture, "動画のサムネの画像" %>
            <%= f.file_field :picture, class: "form-control mb-4", require: true %>
            <%= f.label :title, "タイトル" %>
            <%= f.text_field :title, placeholder: "YouTube動画のタイトル", class: "form-control", required: true %>
        </div>
        <div class="col-12 col-md-6 my-auto">
            <%= f.label :link, "動画のURL" %>
            <%= f.text_field :link, class: "form-control mb-4", require: true %>
            <%= f.label :content, "概要・メモ" %>
            <%= f.text_area :content, placeholder: "観たくなるような誘い文句を！", class: "form-control" %>
        </div>
        <%= f.submit "保存する", class: "btn btn-outline-dark bg-color put-center mt-4" %>
    </div>
<% end %>

app/views/admin/videos/edit.html.erb
<section class="container text-center pt-5 mb-5">
    <h1 class="pt-5 mt-5 title">動画情報変更</h1>
    <div class="card mt-5 mx-5">
        <div class="card-header py-1">
        
        </div>
        <div class="card-body">
            <%= render "admin/videos/video_form" %>
        </div>
    </div>
</section>

app/views/admin/videos/index.html.erb
<section class="admin-video-index container text-center pt-5 mb-5">
    <h1 class="pt-5 mt-5 title">YouTube動画リスト</h1>
    <div class="card mt-5 mx-5">
        <div class="card-header py-1">
            <div class="row">
                <div class="col-4 col-md-2 text-right ml-auto">
                    <%= link_to "新規", new_admin_video_path, class: "btn btn-outline-dark bg-color py-0 my-1" %>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-md-4 my-auto">サムネ</div>
                <div class="col-6 col-md-2 my-auto">タイトル</div>
                <div class="col-6 col-md-3 my-auto">リンク</div>
                <div class="col-6 col-md-3 my-auto">概要</div>
            </div>
        </div>
        <div class="card-body ">
            <% unless @videos.any? %>
                <h4 class="text-muted">まだ投稿がありません。</h4>
            <% else %>
                <% @videos.each do |video| %>
                    <div class="row">
                        <div class="col-6 col-md-4 my-auto">
                            <%= image_tag video.picture.url, class: "w-100" %>
                        </div>
                        <div class="col-6 col-md-2 my-auto">
                            <%= video.title %>
                        </div>
                        <div class="col-6 col-md-3 my-auto">
                            <%= link_to "#{video.link}", target: :_blank do %>
                                <%= video.link %>
                            <% end %>
                        </div>
                        <div class="col-6 col-md-3 my-auto">
                            <%= video.content %>
                        </div>
                        <div class="col-6 col-md-2 text-left ml-auto my-auto btn-inline">
                            <%= link_to "変更", edit_admin_video_path(video), class: "btn btn-outline-dark py-1" %>
                            <%= button_to "削除", admin_video_path(video), method: :delete, data: {confirm: "本当にこの動画情報を削除しますか?"}, class: "btn btn-outline-dark py-1" %>
                        </div>
                    </div>
                    <hr>
                <% end %>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-6 mx-auto px-auto mt-5">
            <div class="put-center"><%= will_paginate @videos %></div>
        </div>
    </div>
</section>

app/views/admin/videos/new.html.erb
<section class="container text-center pt-5 mb-5">
    <h1 class="pt-5 mt-5 title">動画追加</h1>
    <div class="card mt-5 mx-5">
        <div class="card-header py-1">
        
        </div>
        <div class="card-body">
            <%= render "admin/videos/video_form" %>
        </div>
    </div>
</section>

app/views/videos/index.html.erb
<section class="admin-home container text-center pt-5">
    <h1 class="mb-5 pt-5 title text-white">BOFBOF<br>YouTube企画</h1>
    <div class="mt-3">
        <div class="ml-5 pl-5">
            <%= image_tag "teacher1.png", class:"w-100 ml-5" %><br>
        </div>
        <div class="content text-center font-weight-bold">
            <p  class="mt-4 section-title-s mb-5 pb-5">
                <br><span class="text-white">ニュース ✖︎ 若者＝？？</span><br>
                普段ニュースを見ない若者世代に向けた<br>
                『あなた』と話題のニュースとの関連点を探る動画です<br>
                少しでも興味が湧いたらチャンス! <br>
                ワンクリックで動画にとぼう!
            </p>
        </div>
    </div>
    <div class="search-box pl-3 mx-5 mb-4" id="search">
        <%= search_form_for @q, url: videos_url(anchor: "search") do |f| %>
            <div class="row">
                <div class="col-5 col-md-4 mr-0 pr-0">
                    <%= f.search_field :title_or_content_cont, placeholder: "キーワードで検索", class: "form-control text-center" %>
                </div>
                <div class="col-2 col-md-1 ml-0 pl-0">
                    <%= f.submit "検索",　name: "", class: "btn btn-outline-dark bg-color ml-0" %>
                </div>
            </div>
        <% end %>
    </div>
    <div class="row mx-5">
        <% @videos.each do |video| %>
            <div class="col-12 col-md-4 px-3">
                <div class="bg-white p-4 mx-1">
                <%= link_to "#{video.link}", target: :_blank do %>
                    <%= image_tag video.picture.url, class:"w-100 hover" %><br>
                <% end %>
                <%= link_to "#{video.link}", class: "text-dark font-weight-bold", target: :_blank do %>
                    <%= video.title %><br>
                <% end %>
                <small class="text-dark"><%= video.content %></small>
                </div>
            </div>
        <% end %>
    </div>
    <div class="row">
        <div class="col-6 mx-auto px-auto mt-5">
            <div class="put-center"><%= will_paginate @users %></div>
        </div>
    </div>
</section>