config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  get 'notices/show'
  root 'pages#home'
  get '/about', to: "pages#about"
  get '/discord', to: "pages#discord"

  namespace :admin do
    get 'pages/home'
    get 'users/index'
    get 'contacts/index'
    patch 'contacts/update'

    resources :posts, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch "publicate"
        patch "withdraw"
      end

      resources :dtopics, only: [:create, :destroy] do
        member do
          patch "d_choose"
          patch "d_omit"
        end
      end

      resources :itopics, only: [:create, :destroy] do
        member do
          patch "i_choose"
          patch "i_omit"
        end
      end
      
      resources :comments, only: [:create, :destroy] 
    end

    resources :users do
      member do
        patch "set_admin"
        patch "remove_admin"
      end
    end

    resources :notices, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch "publicate"
        patch "withdraw"
      end
    end

    resources :videos
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :videos, only: [:index]
  resources :posts, only: [:index]
  resources :contacts, only: [:create]
  resources :notices, only: [:index, :show]

  namespace :likes do
    post 'comment_like'
    delete 'comment_dislike'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :likes, as: :object, dependent: :destroy

  validates :content, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :content, presence: true

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: {maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/models/dtopic.rb
class Dtopic < ApplicationRecord
  belongs_to :post

  validates :content, presence: true, length: { maximum: 42 }
end

app/models/itopic.rb
class Itopic < ApplicationRecord
  belongs_to :post

  validates :content, presence: true, length: { maximum: 42 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :object, polymorphic: true
  default_scope { order(created_at: :desc) }
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :dtopics, dependent: :destroy
  has_many :itopics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, as: :object, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :contacts, dependent: :destroy
  
  mount_uploader :picture, PictureUploader
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 170 }

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: {maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :picture, PictureUploader

  validates :link, presence: true
  validates :title, presence: true
  validates :picture, presence: true
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < ApplicationController

  def index
    @filter = params[:notice_filter]
    if @filter == "published"
      @notices = Notice.where(to_show: true).paginate(page: params[:page], per_page: 8)
    elsif @filter == "unpublished"
      @notices = Notice.where(to_show: false).paginate(page: params[:page], per_page: 8)
    else
      @notices = Notice.paginate(page: params[:page], per_page: 8)
    end
  end

  def new
    @notice = Notice.new
  end

  def create
    @notice = Notice.new(notice_params)
    if @notice.save
       @notice.update(to_show: false)

      redirect_to admin_notices_url
    else
      render "new"
    end
  end

  def show

  end
  
  def edit
    @notice = Notice.find(params[:id])
  end

  def update
    @notice = Notice.find(params[:id])
    @notice.update(notice_params)

    flash[:success] = "お知らせを編集しました！"
    
    redirect_to admin_notices_url
  end

  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy
    flash[:success] = "お知らせを削除しました！"

    redirect_back(fallback_location: request.referer)
  end

  def publicate
    @notice = Notice.find(params[:id])
    @notice.update(to_show: true)
    flash[:success] = "お知らせを掲載しました！"

    redirect_to admin_notices_url
  end

  def withdraw
    @notice = Notice.find(params[:id])
    @notice.update(to_show: false)
    flash[:success] = "お知らせを隠しました！"

    redirect_to admin_notices_url
  end

  private
  def notice_params
    params.require(:notice).permit(:title, :content, :to_show, :link)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def comment_like
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    @comment.likes.create(user_id: current_user.id)

    redirect_to edit_admin_post_url(@post, anchor: "comment")
  end

  def comment_dislike
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    @like = Like.find(params[:like_id])
    @like.destroy

    redirect_to edit_admin_post_url(@post, anchor: "comment")
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  def index
    @active_notices = Post.where(is_active: true)
    @notices = @q.result(distinct: true).paginate(page: params[:page], per_page: 6)
  end

  def show
    @notice = Notice.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @notices = Notice.where(to_show: true)
    @contact = Contact.new
    @users = User.where(is_admin: true).paginate(page: params[:page], per_page: 4)
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @active_posts = Post.where(is_active: true)
    @q = @active_posts.ransack(params[:q])
    @posts = @q.result(distinct: true).paginate(page: params[:page], per_page: 6)
  end
end

app/helpers/admin/notices_helper.rb
module Admin::NoticesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    # 渡された情報(user)のidでログインする
    session[:user_id] = user.id
  end

  def current_user
    # 変数の値がnilなら変数に代入するが、nilでなければ代入しない (変数の値を変えない)
    # @current_user=current_user OR User.find_by(id: session[user_id])をやってる
    # @current_user =@current_user || User.find_by(id: session[user_id]と下のコードは等しい
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    # ユーザーがログインしていればtrue、その他ならfalseを返す
    !current_user.nil?
  end

  def logout(user)
    session.delete(:user_id)
    # こやつを書いていなかった吉田は１週間以上エラーでした
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def btn_color(status)
    @filter == status ? "btn-dark" : "btn-outline-dark"
  end

  def admin_user(user)
    if user.is_admin == true
      "font-weight-bold"
    end
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/notices/_notice_form.html.erb
<%= form_for([:admin, @notice]) do |n| %>
    <div class="row justify-content-center mx-5">
        <div class="col-12 col-md-6 my-auto pb-2">
            <%= n.label :title, "タイトル" %>
            <%= n.text_field :title, placeholder: "例: 0月0日の説明会のお知らせ", class: "form-control", required: true %>
        </div>
        <div class="col-12 col-md-6 my-auto pb-2">
            <%= n.label :content, "内容" %>
            <%= n.text_area :content, placeholder:"0月0日に説明会を行います", class: "form-control" %>
        </div>
        <div class="col-12 col-md-6 my-auto pb-2">
            <%= n.label :link, "zoomなどのURL" %>
            <%= n.text_field :link, class: "form-control", require: true %>
        </div>
        <%= n.submit "保存する", class: "btn btn-outline-dark bg-color put-center mt-4" %>
    </div>
<% end %>

app/views/admin/notices/edit.html.erb
<section class="admin-post-index container text-center pt-5 mb-5">
    <h1 class="pt-5 title">お知らせ編集</h1>
    <div class="card mt-5 mx-5">
        <div class="card-header py-1">
        
        </div>
        <div class="card-body mb-3">
            <%= render "admin/notices/notice_form" %>
            <hr>
        <div class="mr-5 text-right">
                <% if @notice.to_show == false %>
                    <%= button_to "投稿を載せる", publicate_admin_notice_path(@notice), method: :patch, class: "btn btn-outline-dark bg-color put-center mt-4" %>
                <% else %>
                    <%= button_to "投稿を隠す", withdraw_admin_notice_path(@notice), method: :patch, class: "btn btn-outline-dark put-center mt-4" %>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/admin/notices/index.html.erb
<section class="admin-post-index container text-center pt-5 mb-5">
    <h1 class="pt-5 title">お知らせリスト</h1>
    <div class="row mx-3">
        <div class="col-12 col-md-4 mt-5 mb-2 px-5">
            <div class="row justify-content-center">
                <div class="col-4 px-0">
                    <%= link_to "すべて", admin_notices_path(notice_filter: "all"), class:"btn btn-block #{post_btn_color("all")}" %>
                </div>
                <div class="col-4 px-0">
                    <%= link_to "掲載済み", admin_notices_path(notice_filter: "published"), class:"btn btn-block #{post_btn_color("published")}" %>
                </div>
                <div class="col-4 px-0">
                    <%= link_to "編集中", admin_notices_path(notice_filter: "unpublished"), class:"btn btn-block #{post_btn_color("unpublished")}" %>
                </div>
            </div>
        </div>
    </div>
    <div class="card mx-5">
        <div class="card-header py-1">
            <div class="row">
                <div class="col-4 col-md-3 text-right ml-auto">
                    <%= link_to "新規", new_admin_notice_path, class: "btn btn-outline-dark py-1 bg-color mb-1" %>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-6 col-md-2 my-auto pl-4">ステータス</div>
                <div class="col-6 col-md-2 my-auto">タイトル</div>
                <div class="col-12 col-md-5 my-auto">内容</div>
                <div class="col-6 col-md-3 my-auto">zoomなどのリンク</div>
            </div>
        </div>
        <div class="card-body">   
            <% if !@notices.any? %>
                <h4 class="text-muted">まだ投稿がありません。</h4>
            <% else %>
                <% @notices.each do |notice| %>
                    <div class="row justify-content-center py-0">
                        <div class="col-6 col-md-2 my-auto">
                            <% if notice.to_show == true %>
                                <span class="orange">掲載済み</span>
                            <% else %>
                                <span class="text-muted">編集中...</span>
                            <% end %>
                        </div>
                        <div class="col-6 col-md-2 my-auto">
                            <%= notice.title %>
                        </div>
                        <div class="col-12 col-md-5 my-auto">
                            <%= notice.content %>
                        </div>
                        <div class="col-12 col-md-3 my-auto">
                            <%= link_to "#{notice.link}", class: "col-7 col-md-5 font-weight-bold", target: :_blank do %>
                                <%= notice.link %><br>
                            <% end %>
                        </div>
                        <div class="col-6 col-md-4 ml-auto my-auto">
                            <div class="row pt-2">
                                <div class="col-6">
                                    <%= link_to "編集", edit_admin_notice_path(notice), class: "btn btn-outline-dark bg-color py-0 btn-block" %>
                                </div>
                                <div class="col-6">
                                    <%= button_to "削除", admin_notice_path(notice), method: :delete, data: {confirm: "本当にこの投稿を削除しますか?"}, class: "btn btn-outline-dark py-0 btn-block" %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                <% end %>
            <% end %>

        </div>
    </div>
    <div class="row">
        <div class="col-6 mx-auto px-auto mt-5">
            <div class="put-center">
                <%= will_paginate @posts %>
            </div>
        </div>
    </div>
</section>

app/views/admin/notices/new.html.erb
<section class="container text-center pt-5 mb-5">
    <h1 class="pt-5 title">お知らせ投稿を追加</h1>
    <div class="card mt-5 mx-5">
        <div class="card-header py-1">
        
        </div>
        <div class="card-body">
            <%= render "admin/notices/notice_form" %>
        </div>
    </div>
</section>

app/views/notices/index.html.erb
<h1>これいらんかったかもしれん</h1>
<p>Find me in app/views/notices/index.html.erb</p>

app/views/notices/show.html.erb
<section class="notice-title">
    <div class="container mt-5 mb-3 p-5 bg-color text-white">
            <div class="content text-center" id="contact">
                <h1 class="section-title">
                    <%= @notice.title %>
                </h1>
            </div>
        </div>
</section>
<section class="notice-description">
    <div class="container mb-5 p-5 bg-white">
            <div class="content text-center">
                <h4 class="mt-3 px-5">
                    <span><%= @notice.content %></span>
                </h4>
                <div class="row">
                    <div class="col-8 ml-auto col-md-6">
                        <p>
                            <%= link_to "#{@notice.link}", class: "col-7 col-md-5 orange font-weight-bold", target: :_blank do %>
                                <h4>リンクをチェック</h4>
                            <% end %>
                        </p>
                    </div>
                </div>
            </div>
        </div>
</section>